/**
 * Gate 2a — shape pipeline vs golden exportshape fixtures.
 *
 * For every corpus glyph in test/golden/ (one fixture per unique glyph, since
 * the shape is size-independent after em-normalization):
 *   1. Parse the glyph from the font.
 *   2. Em-normalize (÷ unitsPerEm).
 *   3. normalizeShape() — deconvergence + split single-edge contours.
 *   4. Compare against the shape.txt golden (ignoring colour codes):
 *      - Same contour count.
 *      - Same edge count per contour.
 *      - Same edge types per contour.
 *      - Control-point coordinates within COORD_TOLERANCE.
 *
 * The shape.txt was generated by msdfgen -exportshape AFTER edge coloring,
 * but the geometry is identical.  We ignore colours because M3 handles them.
 *
 * NEVER modify test/golden/** — only the human regenerates fixtures.
 */

import { readFileSync, readdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { describe, it, expect } from "vitest";
import { Font } from "../../src/font/font.js";
import { emNormalizeShape, normalizeShape } from "../../src/shape/normalize.js";
import { parseShapeDesc } from "../utils/shapedesc.js";
import { LINEAR, QUADRATIC, CUBIC } from "../../src/shape/segments.js";
import type { Shape } from "../../src/shape/shape.js";
import type { EdgeSegment } from "../../src/shape/segments.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GOLDEN_DIR = resolve(__dirname, "../golden");
const FONTS_DIR = resolve(__dirname, "../fonts");

/** Maximum absolute difference allowed for any control-point coordinate. */
const COORD_TOLERANCE = 1e-9;

// ── Fixture loading ──────────────────────────────────────────────────────────

interface GoldenFixture {
  fontId: string;
  fontFile: string;
  glyphId: number;
  shapeText: string;
}

/**
 * Loads one fixture per (fontId, glyphId) from test/golden/.
 * Uses the 32px variant (shape is identical across sizes).
 */
function loadFixtures(): GoldenFixture[] {
  const fixtures: GoldenFixture[] = [];
  const seen = new Set<string>();

  for (const fontId of readdirSync(GOLDEN_DIR)) {
    const fontDir = resolve(GOLDEN_DIR, fontId);
    try {
      if (!readdirSync(fontDir).length) continue;
    } catch {
      continue;
    }

    // Determine font file from any meta.json in this font's fixtures.
    let fontFile = "";
    const glyphDirs = readdirSync(fontDir);

    // Prefer 32px fixtures (to deduplicate — shape is size-independent).
    const dirs32 = glyphDirs.filter((d) => d.endsWith("_32px"));
    if (dirs32.length === 0) continue;

    for (const glyphDir of dirs32) {
      const fixDir = resolve(fontDir, glyphDir);
      const metaPath = resolve(fixDir, "meta.json");
      const shapePath = resolve(fixDir, "shape.txt");
      if (!existsSync(metaPath) || !existsSync(shapePath)) continue;

      const meta = JSON.parse(readFileSync(metaPath, "utf8")) as {
        font: string;
        charSpec: string;
      };

      // Resolve font file relative to test/fonts/
      if (!fontFile) {
        const absFont = meta.font;
        fontFile = resolve(FONTS_DIR, absFont.split("/").pop()!);
      }

      // Parse glyph index from charSpec.
      // Text fonts: charSpec is a decimal codepoint string (e.g. "33").
      // Icon fonts: charSpec is "g<N>" (e.g. "g1").
      let glyphId: number;
      const cs = meta.charSpec;
      if (cs.startsWith("g")) {
        glyphId = parseInt(cs.slice(1), 10);
      } else {
        // charSpec is codepoint; we resolve glyphId when we have the font.
        // Store codepoint as negative to distinguish later.
        glyphId = -parseInt(cs, 10);
      }

      const key = `${fontId}:${glyphId}`;
      if (seen.has(key)) continue;
      seen.add(key);

      const shapeText = readFileSync(shapePath, "utf8");
      fixtures.push({ fontId, fontFile, glyphId, shapeText });
    }
  }

  return fixtures;
}

// ── Shape comparison ──────────────────────────────────────────────────────────

function typeName(type: number): string {
  switch (type) {
    case LINEAR:
      return "LINEAR";
    case QUADRATIC:
      return "QUADRATIC";
    default:
      return "CUBIC";
  }
}

/**
 * Compare two shapes point-by-point, returning null on success or an error string.
 */
function compareShapes(ours: Shape, golden: Shape): string | null {
  if (ours.contours.length !== golden.contours.length) {
    return `contour count mismatch: ours=${ours.contours.length} golden=${golden.contours.length}`;
  }
  for (let ci = 0; ci < ours.contours.length; ci++) {
    const oc = ours.contours[ci]!;
    const gc = golden.contours[ci]!;
    if (oc.length !== gc.length) {
      return `contour ${ci}: edge count mismatch: ours=${oc.length} golden=${gc.length}`;
    }
    for (let ei = 0; ei < oc.length; ei++) {
      const os = oc[ei]!;
      const gs = gc[ei]!;
      if (os.type !== gs.type) {
        return `contour ${ci} edge ${ei}: type mismatch: ours=${typeName(os.type)} golden=${typeName(gs.type)}`;
      }
      const err = comparePoints(ci, ei, os, gs);
      if (err) return err;
    }
  }
  return null;
}

function comparePoints(ci: number, ei: number, os: EdgeSegment, gs: EdgeSegment): string | null {
  const pairs: Array<[string, number, number]> = [
    ["p0x", os.p0x, gs.p0x],
    ["p0y", os.p0y, gs.p0y],
    ["p1x", os.p1x, gs.p1x],
    ["p1y", os.p1y, gs.p1y],
  ];
  if (os.type === QUADRATIC || os.type === CUBIC) {
    pairs.push(["p2x", os.p2x, gs.p2x], ["p2y", os.p2y, gs.p2y]);
  }
  if (os.type === CUBIC) {
    pairs.push(["p3x", os.p3x, gs.p3x], ["p3y", os.p3y, gs.p3y]);
  }
  for (const [name, ov, gv] of pairs) {
    const diff = Math.abs(ov - gv);
    if (diff > COORD_TOLERANCE) {
      return `contour ${ci} edge ${ei} ${name}: ours=${ov} golden=${gv} diff=${diff}`;
    }
  }
  return null;
}

// ── Tests ────────────────────────────────────────────────────────────────────

const fixtures = loadFixtures();

// Cache loaded fonts
const fontCache = new Map<string, Font>();
function getFont(fontFile: string): Font {
  let f = fontCache.get(fontFile);
  if (!f) {
    const buf = readFileSync(fontFile);
    const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
    f = new Font(ab);
    fontCache.set(fontFile, f);
  }
  return f;
}

describe("Gate 2a — shape normalization vs exportshape goldens", () => {
  // Group fixtures by fontId for better output
  const byFont = new Map<string, GoldenFixture[]>();
  for (const fix of fixtures) {
    const list = byFont.get(fix.fontId) ?? [];
    list.push(fix);
    byFont.set(fix.fontId, list);
  }

  for (const [fontId, fontFixtures] of byFont) {
    describe(fontId, () => {
      for (const fix of fontFixtures) {
        // Determine a human-readable glyph label
        const glyphLabel =
          fix.glyphId < 0
            ? `U+${(-fix.glyphId).toString(16).toUpperCase().padStart(4, "0")}`
            : `g${fix.glyphId}`;

        it(`${glyphLabel} shape matches golden`, () => {
          const font = getFont(fix.fontFile);

          // Resolve glyph index: negative = codepoint
          const glyphId = fix.glyphId < 0 ? font.glyphId(-fix.glyphId) : fix.glyphId;

          // Build our shape
          const shape = font.shape(glyphId);
          emNormalizeShape(shape, font.metrics.unitsPerEm);
          normalizeShape(shape);

          // Parse golden shape (ignoring colours)
          const { shape: golden } = parseShapeDesc(fix.shapeText);

          // Glyphs with no outline (space, .notdef) may have 0 contours in both.
          // The golden might still have contours if it's a special glyph. Allow 0=0.
          const err = compareShapes(shape, golden);
          expect(err, `[${fontId}/${glyphLabel}] ${err ?? ""}`).toBeNull();
        });
      }
    });
  }
});
